variables:
  DEBIAN_FRONTEND: noninteractive
  COURSIER_VERSION: 1.0.0-RC1

image: hseeberger/scala-sbt

compile:
  stage: build
  before_script:
    - mkdir -p ~/.sbt/0.13/plugins
    - echo "addSbtPlugin(\"io.get-coursier\" % \"sbt-coursier\" % \"$COURSIER_VERSION\")" >> ~/.sbt/0.13/plugins/coursier.sbt
  script:
    - java -version
    - javac -version
    - ./sbt compile
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - project/project/
      - project/target/
      - target/
    expire_in: 1 day
  tags:
    - docker

unit:
  stage: test
  before_script:
    - mkdir -p ~/.sbt/0.13/plugins
    - echo "addSbtPlugin(\"io.get-coursier\" % \"sbt-coursier\" % \"$COURSIER_VERSION\")" >> ~/.sbt/0.13/plugins/coursier.sbt
  script:
    - java -version
    - javac -version
    - ./sbt test
  tags:
    - docker
