variables:
  DEBIAN_FRONTEND: noninteractive

image: hseeberger/scala-sbt

compile:
  stage: build
  script:
    - java -version
    - javac -version
    - ./sbt compile
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - target/
    expire_in: 1 day
  tags:
    - docker
