variables:
  DEBIAN_FRONTEND: noninteractive
  COURSIER_VERSION: 1.0.0-RC8

.scala-job: &scala
  image: hseeberger/scala-sbt
  before_script:
    - mkdir -p ~/.sbt/0.13/plugins
    - echo "addSbtPlugin(\"io.get-coursier\" % \"sbt-coursier\" % \"$COURSIER_VERSION\")" >> ~/.sbt/0.13/plugins/coursier.sbt
    - java -version
    - javac -version

compile:
  <<: *scala
  stage: build
  script:
    - ./sbt compile
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - project/project/
      - project/target/
      - target/
    expire_in: 1 day
  tags:
    - docker

unit:
  <<: *scala
  stage: test
  script:
    - ./sbt test
  tags:
    - docker

check_example:
  <<: *scala
  stage: test
  script:
    - ./sbt "run -m example/registration.model"
  tags:
    - docker

fat_jar:
  <<: *scala
  stage: deploy
  variables:
    SCALA_VERSION: "2.12"
    JAR_NAME: "swsg"
  script:
    - ./sbt assembly
    - java -jar target/scala-$SCALA_VERSION/$JAR_NAME.jar --help
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - target/scala-$SCALA_VERSION/$JAR_NAME.jar
    expire_in: 15 day
  tags:
    - docker
