variables:
  DEBIAN_FRONTEND: noninteractive
  COMPOSER_NO_INTERACTION: "1"
  COURSIER_VERSION: 1.0.0-RC11
  SCALA_VERSION: "2.12"
  JAR_NAME: "swsg"
  NODE_VERSION: "8"

stages:
  - build
  - example
  - test_example

.scala-job: &scala
  image: hseeberger/scala-sbt:8u141-jdk_2.12.3_1.0.1
  before_script:
    - mkdir -p ~/.sbt/0.13/plugins
    - echo "addSbtPlugin(\"io.get-coursier\" % \"sbt-coursier\" % \"$COURSIER_VERSION\")" >> ~/.sbt/0.13/plugins/coursier.sbt
    - mkdir -p ~/.sbt/1.0/plugins
    - echo "addSbtPlugin(\"io.get-coursier\" % \"sbt-coursier\" % \"$COURSIER_VERSION\")" >> ~/.sbt/1.0/plugins/coursier.sbt
    - java -version
    - javac -version

build:
  <<: *scala
  stage: build
  script:
    - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
    - apt-get update && apt-get install -y nodejs
    - ./sbt test swsgJVM/assembly swsgJS/fastOptJS
    - java -jar jvm/target/scala-$SCALA_VERSION/$JAR_NAME.jar --help
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      #- project/project/
      #- project/target/
      #- js/target/
      - js/target/scala-$SCALA_VERSION/$JAR_NAME-fastopt.js
      - js/target/scala-$SCALA_VERSION/$JAR_NAME-fastopt.js.map
      #- jvm/target/
      - jvm/target/scala-$SCALA_VERSION/$JAR_NAME.jar
    expire_in: 15 day
  tags:
    - docker

check_example:
  <<: *scala
  stage: example
  dependencies:
    - build
  script:
    - java -jar jvm/target/scala-$SCALA_VERSION/$JAR_NAME.jar check --model example/registration.model
  tags:
    - docker

gen_example:
  <<: *scala
  stage: example
  script:
    - java -jar jvm/target/scala-$SCALA_VERSION/$JAR_NAME.jar gen --model example/registration.model --implementation example/impl/ --backend laravel --output example/output/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - example/output/
    expire_in: 1 day
  tags:
    - docker

test_gen_example:
  image: composer
  stage: test_example
  dependencies:
    - gen_example
  script:
    - cd example/output/
    - sed -i 's/App\\Providers\\RouteServiceProvider::class/App\\Providers\\GeneratedRouteServiceProvider::class/' config/app.php
    - composer install --no-progress
    - ./vendor/bin/phpunit
  tags:
    - docker
